open_redirect:
  # override daftar param redirect di modul open_redirect
  param_names: ["url", "next", "redirect", "return", "callbackUrl", "dest", "redir"]

sensitive_paths:
  # override patterns
  patterns:
    - admin
    - panel
    - login
    - dashboard
    - swagger
    - grafana

documents:
  # tambahkan ekstensi ekstra
  extra_ext: ["log", "bak"]

sensitive_params:
  # override daftar nama param sensitif
  sensitive_param_names: ["token", "auth", "jwt", "session", "password", "apikey"]

params:
  # override setting modul params
  min_len: 2
  exclude: ["ts", "lang", "locale"]

emails:
  # domain email tambahan
  email_domains: ["example.org", "vendor.co"]
  # scan path kalau perlu (hati-hati @2x, modul sudah punya filter)
  scan_path: false

robots:
  # lokasi file robots body lokal
  robots_dir: "robots_bodies"
  write_disallow: true
